// lib/services/export_service.dart
// PDF and Excel export for expense reports

import 'dart:io';
import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/expense_model.dart';
import '../models/split_expense_model.dart';
import '../core/constants/app_constants.dart';
import '../core/utils/date_formatter.dart';
import 'expense_service.dart';
import 'split_service.dart';

class ExportService {
  ExportService._();

  // === PDF Export ===

  static Future<void> exportPDF() async {
    final pdf = pw.Document();
    final expenses = ExpenseService.getAllExpenses();
    final splits = SplitService.getAllSplits();
    final now = DateTime.now();
    final fmt = DateFormat('dd MMM yyyy');

    final prefs = await SharedPreferences.getInstance();
    final activeSymbol = prefs.getString(AppConstants.currencyKey) ?? '₹';
    final userName = prefs.getString('user_name') ?? '';
    final pdfCurrencySymbol = _formatPdfCurrency(activeSymbol);

    // Page 1: Cover + Summary
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildPdfHeader(),
        footer: (context) => _buildPdfFooter(context),
        build: (context) => [
          _buildPdfTitle(fmt.format(now), userName),
          pw.SizedBox(height: 20),
          _buildSummarySection(expenses, splits, pdfCurrencySymbol),
          pw.SizedBox(height: 24),
          _buildExpenseTable(expenses),
          pw.SizedBox(height: 24),
          _buildSplitTable(splits),
        ],
      ),
    );

    // Save and share
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = now.toIso8601String().replaceAll(':', '-').substring(0, 19);
    final file = File('${dir.path}/cashier_report_$timestamp.pdf');
    final bytes = await pdf.save();
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: 'Cashier Report - ${fmt.format(now)}',
    );
  }

  static pw.Widget _buildPdfHeader() {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.indigo, width: 2),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            AppConstants.appName,
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.indigo,
            ),
          ),
          pw.Text(
            AppConstants.appTagline,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Cashier',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
        ],
      ),
    );
  }

  static pw.Widget _buildPdfTitle(String date, String userName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          userName.isNotEmpty ? 'Expense Report for $userName' : 'Expense Report',
          style: pw.TextStyle(
              fontSize: 28,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.indigo900),
        ),
        pw.Text('Generated on $date',
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
      ],
    );
  }

  static pw.Widget _buildSummarySection(
      List<ExpenseModel> expenses, List<SplitExpenseModel> splits, String pdfCurrencySymbol) {
    final total = ExpenseService.sumExpenses(expenses);
    final monthTotal = ExpenseService.getThisMonthTotal();
    final splitTotal = SplitService.getTotalSplitAmount();
    final pending = SplitService.getTotalPendingAmount();

    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: const pw.BoxDecoration(
        color: PdfColors.indigo50,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Summary',
              style: pw.TextStyle(
                  fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.Row(
            children: [
              _summaryItem('Total Expenses', '$pdfCurrencySymbol${total.toStringAsFixed(2)}'),
              _summaryItem('This Month', '$pdfCurrencySymbol${monthTotal.toStringAsFixed(2)}'),
              _summaryItem('Total Split', '$pdfCurrencySymbol${splitTotal.toStringAsFixed(2)}'),
              _summaryItem('Pending Split', '$pdfCurrencySymbol${pending.toStringAsFixed(2)}'),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _summaryItem(String label, String value) {
    return pw.Expanded(
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 14, fontWeight: pw.FontWeight.bold,
                  color: PdfColors.indigo900)),
        ],
      ),
    );
  }

  static pw.Widget _buildExpenseTable(List<ExpenseModel> expenses) {
    if (expenses.isEmpty) {
      return pw.Text('No expenses found.',
          style: const pw.TextStyle(color: PdfColors.grey));
    }

    final headers = ['Date', 'Category', 'Place', 'Amount', 'Notes'];
    final rows = expenses.take(100).map((e) => [
      DateFormatter.formatDate(e.dateTime),
      AppConstants.getCategoryById(e.category).name,
      e.place.isEmpty ? '-' : e.place,
      '${_formatPdfCurrency(e.currency)}${e.amount.toStringAsFixed(2)}',
      e.notes.isEmpty ? '-' : e.notes.substring(0, e.notes.length.clamp(0, 30)),
    ]).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Expense History',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(1.5),
            4: const pw.FlexColumnWidth(3),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.indigo),
              children: headers.map((h) => pw.Padding(
                padding: const pw.EdgeInsets.all(6),
                child: pw.Text(h,
                    style: pw.TextStyle(
                        color: PdfColors.white,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 10)),
              )).toList(),
            ),
            ...rows.asMap().entries.map((entry) {
              final isEven = entry.key.isEven;
              return pw.TableRow(
                decoration: pw.BoxDecoration(
                    color: isEven ? PdfColors.white : PdfColors.grey50),
                children: entry.value.map((cell) => pw.Padding(
                  padding: const pw.EdgeInsets.all(5),
                  child: pw.Text(cell,
                      style: const pw.TextStyle(fontSize: 9)),
                )).toList(),
              );
            }),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildSplitTable(List<SplitExpenseModel> splits) {
    if (splits.isEmpty) return pw.SizedBox();

    final headers = ['Date', 'Description', 'Total', 'Members', 'Status'];
    final rows = splits.take(50).map((s) => [
      DateFormatter.formatDate(s.dateTime),
      s.description,
      '${_formatPdfCurrency(s.currency)}${s.totalAmount.toStringAsFixed(2)}',
      s.members.isEmpty ? '-' : s.members.map((m) => m.name).join(', '),
      s.derivedStatus.name.toUpperCase(),
    ]).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Split Expenses',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.teal),
              children: headers.map((h) => pw.Padding(
                padding: const pw.EdgeInsets.all(6),
                child: pw.Text(h,
                    style: pw.TextStyle(
                        color: PdfColors.white,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 10)),
              )).toList(),
            ),
            ...rows.asMap().entries.map((entry) {
              final isEven = entry.key.isEven;
              return pw.TableRow(
                decoration: pw.BoxDecoration(
                    color: isEven ? PdfColors.white : PdfColors.grey50),
                children: entry.value.map((cell) => pw.Padding(
                  padding: const pw.EdgeInsets.all(5),
                  child: pw.Text(cell,
                      style: const pw.TextStyle(fontSize: 9)),
                )).toList(),
              );
            }),
          ],
        ),
      ],
    );
  }

  // === Excel Export ===

  static Future<void> exportExcel() async {
    final excel = Excel.createExcel();

    _buildExpenseSheet(excel);
    _buildSplitSheet(excel);
    _buildStatisticsSheet(excel);

    // Remove default sheet if exists
    if (excel.sheets.containsKey('Sheet1')) {
      excel.delete('Sheet1');
    }

    final dir = await getApplicationDocumentsDirectory();
    final now = DateTime.now();
    final timestamp = now.toIso8601String().replaceAll(':', '-').substring(0, 19);
    final file = File('${dir.path}/cashier_export_$timestamp.xlsx');
    final bytes = excel.save();
    if (bytes != null) {
      await file.writeAsBytes(bytes);
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'Cashier Export - $timestamp',
      );
    }
  }

  static void _buildExpenseSheet(Excel excel) {
    final sheet = excel['Expenses'];
    final expenses = ExpenseService.getAllExpenses();

    // Header row
    final headers = ['ID', 'Date', 'Time', 'Category', 'Place', 'Amount', 'Currency', 'Notes', 'Tags'];
    for (int i = 0; i < headers.length; i++) {
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
        .value = TextCellValue(headers[i]);
    }

    // Data rows
    for (int row = 0; row < expenses.length; row++) {
      final e = expenses[row];
      final rowData = [
        e.id,
        DateFormatter.formatDate(e.dateTime),
        DateFormatter.formatTime(e.dateTime),
        AppConstants.getCategoryById(e.category).name,
        e.place,
        e.amount.toString(),
        e.currencyCode,
        e.notes,
        e.tags.join(', '),
      ];
      for (int col = 0; col < rowData.length; col++) {
        sheet.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row + 1))
          .value = TextCellValue(rowData[col]);
      }
    }
  }

  static void _buildSplitSheet(Excel excel) {
    final sheet = excel['Split Expenses'];
    final splits = SplitService.getAllSplits();

    final headers = ['ID', 'Date', 'Description', 'Payer', 'Total', 'Members', 'Paid', 'Pending', 'Status'];
    for (int i = 0; i < headers.length; i++) {
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))
        .value = TextCellValue(headers[i]);
    }

    for (int row = 0; row < splits.length; row++) {
      final s = splits[row];
      final rowData = [
        s.id,
        DateFormatter.formatDate(s.dateTime),
        s.description,
        s.payer == PayerType.me ? 'Me' : (s.friendName ?? 'Friend'),
        s.totalAmount.toString(),
        s.memberCount.toString(),
        s.paidAmount.toString(),
        s.pendingAmount.toString(),
        s.derivedStatus.name,
      ];
      for (int col = 0; col < rowData.length; col++) {
        sheet.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row + 1))
          .value = TextCellValue(rowData[col]);
      }
    }
  }

  static void _buildStatisticsSheet(Excel excel) {
    final sheet = excel['Statistics'];

    final monthlyTotals = ExpenseService.getMonthlyTotals();
    final categoryTotals = ExpenseService.getCategoryTotalsThisMonth();

    int row = 0;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
      .value = TextCellValue('Monthly Totals');
    row++;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
      .value = TextCellValue('Month');
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
      .value = TextCellValue('Total Amount');
    row++;

    for (final entry in monthlyTotals.entries) {
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
        .value = TextCellValue(entry.key);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
        .value = TextCellValue(entry.value.toStringAsFixed(2));
      row++;
    }

    row += 2;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
      .value = TextCellValue('Category Totals (This Month)');
    row++;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
      .value = TextCellValue('Category');
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
      .value = TextCellValue('Amount');
    row++;

    for (final entry in categoryTotals.entries) {
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
        .value = TextCellValue(AppConstants.getCategoryById(entry.key).name);
      sheet.cell(CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
        .value = TextCellValue(entry.value.toStringAsFixed(2));
      row++;
    }
  }

  static String _formatPdfCurrency(String symbol) {
    switch (symbol) {
      case '₹':
        return 'Rs.';
      case 'د.إ':
        return 'AED';
      case '€':
        return 'EUR';
      case '£':
        return 'GBP';
      case '¥':
        return 'JPY';
      case 'S\$':
        return 'SGD';
      case 'C\$':
        return 'CAD';
      case 'A\$':
        return 'AUD';
      default:
        return symbol;
    }
  }
}
